# permissions for end users to edit hypervs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hyperv-editor-role
rules:
- apiGroups:
  - windows.windows.k8s.io
  resources:
  - hypervs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - windows.windows.k8s.io
  resources:
  - hypervs/status
  verbs:
  - get
